### ISSUE TITLE
App crashes on first run.

### ISSUE THREAD

**Issue by Inversion-NL** [mickem/medin.name.temperature#2]
App crashes on first run.

I'm new to TypeScript so don't know how to debug this.

Since the error is in app.js at line 1 character 5846 doesn't make this easier to debug.
Sorry I can't be of any help at this point.

Let me know if I can help.

```
Allowed temperature span: 18 - 22
Config: , ,
Failed to remove non existing job { Error: cronjob_not_found
    at Remote IPC Process
 message: 'cronjob_not_found', code: 404 }
Updated time to: 0 00 02 * * *
Disabling all triggers
Enabling all triggers
(node:20696) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at g.<anonymous> (/app.js:1:5846)
    at Generator.next (<anonymous>)
    at /app.js:1:1684
    at new Promise (<anonymous>)
    at n (/app.js:1:1429)
    at t.e.devices.on.e (/app.js:1:5679)
    at o (/node_modules/athom-api/dist/index.js:1:1244562)
    at t.value (/node_modules/athom-api/dist/index.js:1:1248460)
    at t.<anonymous> (/node_modules/athom-api/dist/index.js:1:1198613)
    at a (/node_modules/athom-api/dist/index.js:1:324729)
(node:20696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Inversion-NL** [comment]
It looks like it crashes on getting the name for a zone?

Here the list of all the zones I have:
```
{
  "9919ee1e-ffbc-480b-bc4b-77fb047e9e68": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "9919ee1e-ffbc-480b-bc4b-77fb047e9e68",
    "name": "Huis",
    "order": 1,
    "parent": null,
    "active": true,
    "activeLastUpdated": "2019-12-11T08:26:31.577Z",
    "icon": "home"
  },
  "b840a982-a3a7-4513-9d96-902d81128f5c": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "b840a982-a3a7-4513-9d96-902d81128f5c",
    "name": "Eerste verdieping",
    "order": 3,
    "parent": "9919ee1e-ffbc-480b-bc4b-77fb047e9e68",
    "active": true,
    "activeLastUpdated": "2019-12-11T08:27:04.971Z",
    "icon": "stairs-up"
  },
  "6a48add5-7349-4ff3-84b9-812e2d706e50": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "6a48add5-7349-4ff3-84b9-812e2d706e50",
    "name": "Zolder",
    "order": 4,
    "parent": "9919ee1e-ffbc-480b-bc4b-77fb047e9e68",
    "active": true,
    "activeLastUpdated": "2019-12-11T08:26:31.577Z",
    "icon": "roof"
  },
  "9eb2975d-49ea-4033-8db0-105a3e982117": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "9eb2975d-49ea-4033-8db0-105a3e982117",
    "name": "Woonkamer",
    "order": 2,
    "parent": "855113f1-f488-4223-b675-2f01270f573e",
    "active": false,
    "activeLastUpdated": null,
    "icon": "living"
  },
  "2ab5a003-0120-4c01-80f2-a237dcf4ba14": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "2ab5a003-0120-4c01-80f2-a237dcf4ba14",
    "name": "Keuken",
    "order": 3,
    "parent": "855113f1-f488-4223-b675-2f01270f573e",
    "active": false,
    "activeLastUpdated": null,
    "icon": "kitchen"
  },
  "ddc3cdaa-8172-4c4a-97c9-22d8ec462972": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "ddc3cdaa-8172-4c4a-97c9-22d8ec462972",
    "name": "Ouder slaapkamer",
    "order": 2,
    "parent": "b840a982-a3a7-4513-9d96-902d81128f5c",
    "active": true,
    "activeLastUpdated": "2019-12-11T08:29:37.564Z",
    "icon": "bed"
  },
  "5204dc44-8e9c-49e7-aed8-9d5c93330126": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "5204dc44-8e9c-49e7-aed8-9d5c93330126",
    "name": "Achtertuin",
    "order": 5,
    "parent": "9919ee1e-ffbc-480b-bc4b-77fb047e9e68",
    "active": false,
    "activeLastUpdated": null,
    "icon": "garden"
  },
  "855113f1-f488-4223-b675-2f01270f573e": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "855113f1-f488-4223-b675-2f01270f573e",
    "name": "Begane grond",
    "order": 2,
    "parent": "9919ee1e-ffbc-480b-bc4b-77fb047e9e68",
    "active": false,
    "activeLastUpdated": "2019-12-11T11:23:26.911Z",
    "icon": "default"
  },
  "1815c884-af06-4d53-a2c1-6f4c77e9eb4e": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "1815c884-af06-4d53-a2c1-6f4c77e9eb4e",
    "name": "Bram",
    "order": 4,
    "parent": "b840a982-a3a7-4513-9d96-902d81128f5c",
    "active": true,
    "activeLastUpdated": "2019-12-11T08:30:44.115Z",
    "icon": "books"
  },
  "478cfd92-6475-4214-80d9-27125e39863a": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "478cfd92-6475-4214-80d9-27125e39863a",
    "name": "Hal",
    "order": 1,
    "parent": "855113f1-f488-4223-b675-2f01270f573e",
    "active": false,
    "activeLastUpdated": "2019-12-11T11:23:26.911Z",
    "icon": "default"
  },
  "c6c54a9a-db73-4fca-bdd8-7ec791e7e97c": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "c6c54a9a-db73-4fca-bdd8-7ec791e7e97c",
    "name": "Tess",
    "order": 3,
    "parent": "b840a982-a3a7-4513-9d96-902d81128f5c",
    "active": true,
    "activeLastUpdated": "2019-12-11T08:27:04.971Z",
    "icon": "bed"
  },
  "95dbf4ee-8213-4fca-97f0-e0a12cbeed43": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "95dbf4ee-8213-4fca-97f0-e0a12cbeed43",
    "name": "Hal",
    "order": 1,
    "parent": "6a48add5-7349-4ff3-84b9-812e2d706e50",
    "active": false,
    "activeLastUpdated": null,
    "icon": "default"
  },
  "dbdf3538-1968-42a3-83f8-b836276cb45d": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "dbdf3538-1968-42a3-83f8-b836276cb45d",
    "name": "Sem",
    "order": 3,
    "parent": "6a48add5-7349-4ff3-84b9-812e2d706e50",
    "active": true,
    "activeLastUpdated": "2019-12-11T08:26:31.577Z",
    "icon": "bed"
  },
  "9f06f92d-326e-44e6-8933-8b19db2f660c": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "9f06f92d-326e-44e6-8933-8b19db2f660c",
    "name": "Hal",
    "order": 1,
    "parent": "b840a982-a3a7-4513-9d96-902d81128f5c",
    "active": false,
    "activeLastUpdated": null,
    "icon": "default"
  },
  "c39cde2c-8b53-4a32-88e9-723815c599e1": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "c39cde2c-8b53-4a32-88e9-723815c599e1",
    "name": "Voortuin",
    "order": 1,
    "parent": "9919ee1e-ffbc-480b-bc4b-77fb047e9e68",
    "active": false,
    "activeLastUpdated": null,
    "icon": "garden"
  },
  "69a993ac-dcaa-440c-a95a-16defc6ea352": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "69a993ac-dcaa-440c-a95a-16defc6ea352",
    "name": "Voorzolder",
    "order": 2,
    "parent": "6a48add5-7349-4ff3-84b9-812e2d706e50",
    "active": false,
    "activeLastUpdated": null,
    "icon": "default"
  },
  "0c0a3f19-03ce-414c-93f0-d42fba9f76bd": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "0c0a3f19-03ce-414c-93f0-d42fba9f76bd",
    "name": "Garage",
    "order": 6,
    "parent": "9919ee1e-ffbc-480b-bc4b-77fb047e9e68",
    "active": false,
    "activeLastUpdated": null,
    "icon": "home"
  },
  "ac9e3a93-6dfc-4810-9cb7-a0caf449d334": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "ac9e3a93-6dfc-4810-9cb7-a0caf449d334",
    "name": "Badkamer",
    "order": 7,
    "parent": "b840a982-a3a7-4513-9d96-902d81128f5c",
    "active": false,
    "activeLastUpdated": null,
    "icon": "shower"
  },
  "6dabe338-6c21-42ac-9379-4a61ff767b5e": {
    "__athom_api_type": "HomeyAPI.ManagerZones.Zone",
    "id": "6dabe338-6c21-42ac-9379-4a61ff767b5e",
    "name": "Overige",
    "order": 8,
    "parent": "9919ee1e-ffbc-480b-bc4b-77fb047e9e68",
    "active": false,
    "activeLastUpdated": null,
    "icon": "books"
  }
}
```

**Comment by mickem** [comment]
Right, I think I might have broken something when I added some tests today, I dont have test for the "core" yet so will fix this later today (i.e. read hopefully fixed by tomorrow).

And I will see if I can get some source maps or some such to get a better localization than this... as  character 5846 is not very helpfull :/

**Comment by Inversion-NL** [comment]
I tried the new code but I guess it has to be recompiled?

**Comment by mickem** [comment]
Sorry for this forgot to compile the code, need to get some CI/CD in I guess... anyways, the latest stuff in git might fix the issue, at least I have improved error handling (still need to look at getting source maps in there though)

**Comment by Inversion-NL** [comment]
Works without crashing!
Well done!
